name: Simple Action
on: [push]

jobs: 
    simple-action: 
        runs-on: ubuntu-latest
        steps: 
            - name: Simple JS Action
              id: simpleAction
              uses: actions/hello-world-javascript-action@v1
              with: 
                who-to-greet: Toshi
            - name: log greet time 
              run: echo "${{ steps.simpleAction.outputs.time }}"
